import type { Project } from '../types/project';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    title: 'Mend the Maple Street Sidewalk',
    story: 'The sidewalk along Maple Street has been crumbling for years, creating hazards for families with strollers, wheelchair users, and elderly neighbors who walk to the corner store every morning. We want to repair a 200-foot stretch and add subtle brick inlays that nod to the neighborhood\'s heritage. Every footstep should feel safe and welcoming.',
    location: '200 block of Maple Street',
    neighborhood: 'Old Mill District',
    category: 'paths',
    goalAmount: 350,
    raisedAmount: 215,
    backerCount: 28,
    createdAt: '2026-03-15',
    imageUrl: '',
    creatorName: 'Margaret Chen',
    creatorId: 'user-001',
    updates: [
      { id: 'upd-001', date: '2026-03-20', text: 'Spoke with the city permits office — we\'re cleared to begin once funded!' },
      { id: 'upd-002', date: '2026-04-01', text: 'A local mason offered to donate half their labor costs. Community magic!' },
    ],
    backers: [
      { id: 'bk-001', name: 'Thomas Wright', amount: 25, message: 'My grandmother walks this path every day. Thank you!', date: '2026-03-16', isAnonymous: false },
      { id: 'bk-002', name: 'Sarah Lin', amount: 10, message: 'Small weave, big heart.', date: '2026-03-17', isAnonymous: false },
      { id: 'bk-003', name: 'A Neighbor', amount: 5, message: '', date: '2026-03-18', isAnonymous: true },
    ],
    isFunded: false,
  },
  {
    id: 'proj-002',
    title: 'Rosewood Community Garden',
    story: 'An empty lot at the corner of Rosewood and 3rd has been collecting litter for a decade. We dream of transforming it into a thriving community garden with raised beds, a rainwater collection system, and a little bench where neighbors can sit and chat. Seeds of connection, literally planted in the earth.',
    location: 'Corner of Rosewood Ave & 3rd Street',
    neighborhood: 'Rosewood Heights',
    category: 'greenery',
    goalAmount: 500,
    raisedAmount: 500,
    backerCount: 67,
    createdAt: '2026-02-10',
    imageUrl: '',
    creatorName: 'Devon Okafor',
    creatorId: 'user-002',
    updates: [
      { id: 'upd-003', date: '2026-02-28', text: 'We hit our goal! Soil delivery is scheduled for next week.' },
      { id: 'upd-004', date: '2026-03-10', text: 'First planting day was a huge success — 30 neighbors showed up!' },
    ],
    backers: [
      { id: 'bk-004', name: 'Maria Gonzalez', amount: 50, message: 'My kids will love watching things grow.', date: '2026-02-11', isAnonymous: false },
      { id: 'bk-005', name: 'James Patel', amount: 20, message: 'Greenery heals.', date: '2026-02-12', isAnonymous: false },
    ],
    isFunded: true,
  },
  {
    id: 'proj-003',
    title: 'The Underpass Mural Project',
    story: 'The underpass on Cedar Boulevard is dark, intimidating, and covered in graffiti tags. We want to commission local artist Lucia Vega to transform it into a vibrant mural celebrating our neighborhood\'s multicultural heritage. Art makes spaces safer — when a place is beautiful, people take care of it.',
    location: 'Cedar Boulevard Underpass',
    neighborhood: 'Cedar Flats',
    category: 'art',
    goalAmount: 400,
    raisedAmount: 312,
    backerCount: 45,
    createdAt: '2026-03-01',
    imageUrl: '',
    creatorName: 'Lucia Vega',
    creatorId: 'user-003',
    updates: [
      { id: 'upd-005', date: '2026-03-15', text: 'Design sketches are done! Sharing them at the community meeting this Saturday.' },
    ],
    backers: [
      { id: 'bk-006', name: 'Raj Kapoor', amount: 15, message: 'Art is the soul of a neighborhood.', date: '2026-03-02', isAnonymous: false },
      { id: 'bk-007', name: 'Elena Dubois', amount: 30, message: 'Can\'t wait to see this!', date: '2026-03-03', isAnonymous: false },
    ],
    isFunded: false,
  },
  {
    id: 'proj-004',
    title: 'Bike Rack Row on Hazel Lane',
    story: 'Hazel Lane has three cafés, a bookshop, and a bakery, but nowhere to lock a bicycle. Cyclists end up chaining bikes to trees and signposts, or just driving instead. We want to install five artisan-forged bike racks shaped like vines — functional and beautiful. Let\'s make it easier to pedal here.',
    location: 'Hazel Lane (between Oak & Pine)',
    neighborhood: 'Hazel Lane District',
    category: 'paths',
    goalAmount: 250,
    raisedAmount: 180,
    backerCount: 33,
    createdAt: '2026-03-20',
    imageUrl: '',
    creatorName: 'Amir Hassan',
    creatorId: 'user-004',
    updates: [
      { id: 'upd-006', date: '2026-04-05', text: 'The local blacksmith is prototyping the vine design. It\'s gorgeous.' },
    ],
    backers: [
      { id: 'bk-008', name: 'Casey O\'Brien', amount: 10, message: 'I bike to the bakery every morning!', date: '2026-03-21', isAnonymous: false },
    ],
    isFunded: false,
  },
  {
    id: 'proj-005',
    title: 'Lantern Path Through Willowbrook Park',
    story: 'Willowbrook Park is lovely during the day but pitch-dark at night. The path connecting Elm Street to the bus stop becomes unusable after sunset. We want to install solar-powered lanterns along the 400-foot path — warm amber light that feels safe without being harsh. Let the park welcome everyone, at every hour.',
    location: 'Willowbrook Park, Elm Street entrance',
    neighborhood: 'Willowbrook',
    category: 'safety',
    goalAmount: 450,
    raisedAmount: 89,
    backerCount: 14,
    createdAt: '2026-04-01',
    imageUrl: '',
    creatorName: 'Nina Johansson',
    creatorId: 'user-005',
    updates: [],
    backers: [
      { id: 'bk-009', name: 'David Kim', amount: 20, message: 'I take this path to the bus. Light would change everything.', date: '2026-04-02', isAnonymous: false },
    ],
    isFunded: false,
  },
  {
    id: 'proj-006',
    title: 'Little Free Library on Birch Corner',
    story: 'Birch Corner is a quiet intersection where neighbors often stop to chat. We want to build a handmade Little Free Library — a weatherproof wooden cabinet filled with books for anyone to borrow or donate. It\'ll have a tiny reading bench and a hand-painted sign: "Take a story, leave a story." Literacy is community fabric.',
    location: 'Intersection of Birch St & Elm Ave',
    neighborhood: 'Birchwood Commons',
    category: 'art',
    goalAmount: 120,
    raisedAmount: 120,
    backerCount: 41,
    createdAt: '2026-01-20',
    imageUrl: '',
    creatorName: 'Priya Sharma',
    creatorId: 'user-006',
    updates: [
      { id: 'upd-007', date: '2026-02-01', text: 'Funded in 12 days! Woodworking starts this weekend.' },
      { id: 'upd-008', date: '2026-02-20', text: 'The library is installed and already overflowing with books. You did this.' },
    ],
    backers: [
      { id: 'bk-010', name: 'Fiona Clarke', amount: 5, message: 'Books change lives.', date: '2026-01-21', isAnonymous: false },
      { id: 'bk-011', name: 'Oscar Reyes', amount: 1, message: 'Every penny weaves a thread.', date: '2026-01-22', isAnonymous: false },
    ],
    isFunded: true,
  },
  {
    id: 'proj-007',
    title: 'Crosswalk Safety Paint at Grove Elementary',
    story: 'The crosswalk in front of Grove Elementary has faded to near-invisible lines. Parents worry every morning during drop-off. We want to repaint it with high-visibility thermoplastic paint and add playful hopscotch patterns on the sidewalk leading up to the school. Safety can be joyful.',
    location: 'Front of Grove Elementary School, Oak Street',
    neighborhood: 'Grove Park',
    category: 'safety',
    goalAmount: 200,
    raisedAmount: 155,
    backerCount: 38,
    createdAt: '2026-03-10',
    imageUrl: '',
    creatorName: 'Robert Tran',
    creatorId: 'user-007',
    updates: [
      { id: 'upd-009', date: '2026-03-25', text: 'PTA endorsed the project! They\'re matching the first $50 in donations.' },
    ],
    backers: [
      { id: 'bk-012', name: 'Angela Morris', amount: 10, message: 'My daughter crosses here every day. Thank you.', date: '2026-03-11', isAnonymous: false },
      { id: 'bk-013', name: 'A Neighbor', amount: 25, message: 'For the kids.', date: '2026-03-12', isAnonymous: true },
    ],
    isFunded: false,
  },
  {
    id: 'proj-008',
    title: 'Pollinator Meadow Strip',
    story: 'The barren grass strip between the sidewalk and the road on Clover Lane could be so much more. We want to replace it with a native wildflower meadow strip — milkweed, black-eyed susans, coneflowers — to support monarchs, bees, and butterflies. A ribbon of life woven through the neighborhood.',
    location: 'Clover Lane, blocks 100–300',
    neighborhood: 'Clover Lane',
    category: 'greenery',
    goalAmount: 180,
    raisedAmount: 42,
    backerCount: 9,
    createdAt: '2026-04-10',
    imageUrl: '',
    creatorName: 'Beatrice Nguyen',
    creatorId: 'user-008',
    updates: [],
    backers: [
      { id: 'bk-014', name: 'Leo Fernandez', amount: 10, message: 'For the butterflies 🦋', date: '2026-04-11', isAnonymous: false },
    ],
    isFunded: false,
  },
];

export const mockUser = {
  id: 'user-current',
  displayName: 'Wandering Weaver',
  joinedAt: '2026-01-01',
  totalDonated: 65,
  projectsBacked: ['proj-001', 'proj-003', 'proj-006'],
  projectsCreated: [],
};
